config:
    name: 'Skeletor CLI'
    version: 1.0.0
frameworks:
    - Laravel54Framework
    - LaravelLumen54Framework
packages:
    - BarryvdhLaravelDebugbarPackage
    - BehatBehatPackage
    - DatadogStatsPackage
    - KielabokkieJsonapiBehatExtensionPackage
    - SentryPackage
defaultPackages:
    - PixelfusionGitHooksPackage
managers:
    - ComposerManager
    - FrameworkManager
    - PackageManager
    - ProviderManager
