config:
    name: 'Skeletor CLI'
    version: 1.3.3
    github_api_url: 'https://api.github.com/repos/pixelfusion/skeletor/tags'
frameworks:
    # - Laravel54Framework
    - Laravel55Framework
    # - LaravelLumen54Framework
    - LaravelLumen55Framework
packages:
    - BarryvdhLaravelDebugbarPackage
    - DatadogStatsPackage
    - KielabokkieJsonapiBehatExtensionPackage
    - LeagueClimatePackage
    - PredisPredisPackage
    - PrettusL5RepositoryPackage
    - SentryPackage
    - SpatieLaravelFractalPackage
    - SpatieLaravelPermissionPackage
defaultPackages:
    - PixelfusionGitHooksPackage
managers:
    - ComposerManager
    - FrameworkManager
    - PackageManager
    - ProviderManager
    - RunManager
