config:
    name: 'Skeletor CLI'
    version: 1.3.0
frameworks:
    - Laravel54Framework
    - Laravel55Framework
    - LaravelLumen54Framework
packages:
    - BarryvdhLaravelDebugbarPackage
    - BehatBehatPackage
    - DatadogStatsPackage
    - KielabokkieJsonapiBehatExtensionPackage
    - PrettusL5RepositoryPackage
    - SentryPackage
    - SpatieLaravelFractalPackage
    - SpatieLaravelPermissionPackage
defaultPackages:
    - PixelfusionGitHooksPackage
managers:
    - ComposerManager
    - FrameworkManager
    - PackageManager
    - ProviderManager
    - RunManager
