config:
    name: 'Skeletor CLI'
    version: 1.3.2
frameworks:
    # - Laravel54Framework
    - Laravel55Framework
    # - LaravelLumen54Framework
    - LaravelLumen55Framework
packages:
    - BarryvdhLaravelDebugbarPackage
    - DatadogStatsPackage
    - KielabokkieJsonapiBehatExtensionPackage
    - LeagueClimatePackage
    - PredisPredisPackage
    - PrettusL5RepositoryPackage
    - SentryPackage
    - SpatieLaravelFractalPackage
    - SpatieLaravelPermissionPackage
defaultPackages:
    - PixelfusionGitHooksPackage
managers:
    - ComposerManager
    - FrameworkManager
    - PackageManager
    - ProviderManager
    - RunManager
