config:
    name: Skeletor CLI
    version: 1.0.0
frameworks:
    - Laravel54Framework
    - LaravelLumen54Framework
packages:
    - BehatBehatPackage
    - KielabokkieJsonapiBehatExtensionPackage
defaultPackages:
    - PixelfusionGitHooksPackage